AWSTemplateFormatVersion: '2010-09-09'
Description: | 
  Creates an ACM certificate for the CloudFront distribution using Route 53 
  DNS validation for the site subdomain and optional apex domain

Parameters:
  DomainName:
    Type: String
  SubDomain:
    Type: String
  CreateApex:
    Type: String
  HostedZoneId:
    Type: String

Conditions:
  CreateApexConfig: !Equals
    - !Ref CreateApex
    - 'yes'

Resources:
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Sub '${SubDomain}.${DomainName}'
      SubjectAlternativeNames:
        Fn::If:
          - CreateApexConfig
          - - Ref: DomainName
          - Ref: AWS::NoValue
      DomainValidationOptions:
        - DomainName: !Sub '${SubDomain}.${DomainName}'
          HostedZoneId: !Ref HostedZoneId
        - Fn::If:
            - CreateApexConfig
            - DomainName: !Ref DomainName
              HostedZoneId: !Ref HostedZoneId
            - Ref: AWS::NoValue
      ValidationMethod: DNS

Outputs:
  CertificateArn:
    Description: ARN of the issued ACM certificate
    Value: !Ref Certificate
