AWSTemplateFormatVersion: '2010-09-09'
Description: ACFS3 - CloudFront with Header Security and site content
Transform: 'AWS::Serverless-2016-10-31'

Parameters:
  CertificateArn:
    Description: Certificate locator
    Type: String
  DomainName:
    Description: Apex domain name 
    Type: String
  SubDomain:
    Description: Subdomain for the site 
    Type: String
  CreateApex:
    Description: Whether to create a Route 53 record for the apex domain (yes/no)
    Type: String
  S3BucketRoot:
    Description: Name of the S3 bucket containing the website content
    Type: String
  S3BucketRootDomainName:
    Description: Regional domain name of the S3 content bucket
    Type: String
  S3BucketRootArn:
    Description: ARN of the S3 content bucket
    Type: String
  S3BucketLogs:
    Description: S3 bucket used for CloudFront access logs
    Type: String
  S3BucketLogsDomainName:
    Description: S3 logging bucket
    Type: String
  Response404File:
    Description: HTML file returned for 404 errors
    Type: String
  Response403File:
    Description: HTML file returned for 403 errors
    Type: String

Conditions:
  CreateApexConfig: !Equals
    - !Ref CreateApex
    - 'yes'

Resources:
  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref 'S3BucketRoot'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action: s3:GetObject
            Principal:
              Service: 'cloudfront.amazonaws.com'
            Effect: Allow
            Resource: !Sub '${S3BucketRootArn}/*'
            Condition:
              StringEquals:
                'AWS:SourceArn': !Sub 'arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}'

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      # https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-properties-cloudfront-distribution-distributionconfig.html
      DistributionConfig:
        Aliases:
          - !Sub '${SubDomain}.${DomainName}'
          - !If [CreateApexConfig, !Ref DomainName, !Ref 'AWS::NoValue']
        DefaultCacheBehavior:
         # Choose if letting CF compress your files or not if you want to upload gzip files to s3
         # NOTE: when cloudfront compresses files it will send compressed or not compressed files to 
         # clients that supports compression or not. This option is more flexible and less prompt to errors
          Compress: true
          DefaultTTL: 86400
          ForwardedValues:
            QueryString: true
          MaxTTL: 31536000
          TargetOriginId: !Sub 'S3-${AWS::StackName}-root'
          ViewerProtocolPolicy: 'redirect-to-https'
          ResponseHeadersPolicyId: !Ref ResponseHeadersPolicy
          # reference custom request policies
          OriginRequestPolicyId: !Ref OriginRequestPolicy
          CachePolicyId: !Ref CachePolicy
          # NOTES
          # - reference an AWS-managed or custom OriginRequest/Cache Policy for geolocation and/or compression fine tunnning
          # - CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6 <-- CachingOptimized, recommended for s3
        CustomErrorResponses:
          - ErrorCachingMinTTL: 60
            ErrorCode: 404
            ResponseCode: 200 # to avoid 404 errors
            ResponsePagePath: !Ref Response404File
          - ErrorCachingMinTTL: 60
            ErrorCode: 403
            ResponseCode: 200 # to avoid 403 errors
            ResponsePagePath: !Ref Response403File
        Enabled: true
        HttpVersion: 'http2'
        DefaultRootObject: 'index.html'
        IPV6Enabled: true
        Logging:
          Bucket: !Ref 'S3BucketLogsDomainName'
          IncludeCookies: false
          Prefix: 'cdn/'
        Origins:
          - DomainName: !Ref 'S3BucketRootDomainName'
            Id: !Sub 'S3-${AWS::StackName}-root'
            OriginAccessControlId: !Ref OriginAccessControl
            # Indicates the origin is an S3 REST endpoint (not a static website endpoint)
            S3OriginConfig: {}
        PriceClass: 'PriceClass_All'
        ViewerCertificate:
          AcmCertificateArn: !Ref 'CertificateArn'
          MinimumProtocolVersion: 'TLSv1.1_2016'
          SslSupportMethod: 'sni-only'
      Tags:
        - Key: YourBrand Website Solution Solution
          Value: ACFS3

  OriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        # Get a unique ID for the OAC Config name.
        # Name must be unique within account
        Name: !Sub
          - amzn-secure-static-site-${guid}
          - guid: !Select [2, !Split ['/', !Ref 'AWS::StackId']]
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  Route53RecordSetGroup:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: !Sub '${DomainName}.'
      RecordSets:
        - Name: !Sub '${SubDomain}.${DomainName}'
          Type: 'A'
          AliasTarget:
            DNSName: !GetAtt 'CloudFrontDistribution.DomainName'
            EvaluateTargetHealth: false
            # The  following HosteZoneId is always used for alias records pointing to CF.
            HostedZoneId: 'Z2FDTNDATAQYW2'

  ApexRoute53RecordSetGroup:
    Condition: CreateApexConfig
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: !Sub '${DomainName}.'
      RecordSets:
        - Name: !Ref 'DomainName'
          Type: 'A'
          AliasTarget:
            DNSName: !GetAtt 'CloudFrontDistribution.DomainName'
            EvaluateTargetHealth: false
            # The  following HosteZoneId is always used for alias records pointing to CF.
            HostedZoneId: 'Z2FDTNDATAQYW2'

  ResponseHeadersPolicy:
    Type: AWS::CloudFront::ResponseHeadersPolicy
    Properties:
      ResponseHeadersPolicyConfig:
        Name: !Sub '${AWS::StackName}-static-site-security-headers'
        SecurityHeadersConfig:
          StrictTransportSecurity:
            AccessControlMaxAgeSec: 63072000
            IncludeSubdomains: true
            Override: true
            Preload: true
          ContentSecurityPolicy:
            # edit as needed. ex.
            # default-src 'self';
            # img-src 'self' https: data: blob:; --> for website imgs, https CDN services
            # script-src 'self' https://maps.googleapis.com https://maps.gstatic.com https://*.google-analytics.com https://*.googletagmanager.com https://*.g.doubleclick.net/ https://*.google.com 'unsafe-eval' 'unsafe-inline' blob:; --> for lottie-web and gMaps execution
            # style-src 'self' https://fonts.googleapis.com 'unsafe-inline'; --> to accept dynamic inline styles added by MUI, Bootstrap, COREUI, google Maps, etc.
            # object-src 'self';
            # worker-src 'self' blob: --> for lottie webworkers
            # font-src 'self' https: data:; --> for https fonts CDN services
            # media-src 'self' blob: https:;
            # child-src 'self' blob:;
            # connect-src 'self' https: blob: data:; --> for lotiefiles cdn services, github contributions
            # frame-src 'self' https://www.googletagmanager.com https://www.youtube.com https://www.youtube-nocookie.com https://open.spotify.com; --> for irames
            ContentSecurityPolicy: "default-src 'self'; img-src 'self' https: data: blob:; script-src 'self' https://maps.googleapis.com https://maps.gstatic.com https://*.google-analytics.com https://*.googletagmanager.com https://*.g.doubleclick.net/ https://*.google.com 'unsafe-eval' 'unsafe-inline' blob:; style-src 'self' https://fonts.googleapis.com 'unsafe-inline'; object-src 'self'; worker-src 'self' blob:; font-src 'self' https: data:; media-src 'self' blob: https:; child-src 'self' blob:; connect-src 'self' https: blob: data:; frame-src 'self' https://www.googletagmanager.com https://www.youtube.com https://www.youtube-nocookie.com https://open.spotify.com;"
            Override: true
          ContentTypeOptions:
            Override: true
          FrameOptions:
            FrameOption: DENY
            Override: true
          ReferrerPolicy:
            ReferrerPolicy: 'same-origin'
            Override: true
          XSSProtection:
            ModeBlock: true
            Override: true
            Protection: true

  # OriginRequestPolicy configured to forward geolocation headers from CloudFront
  OriginRequestPolicy:
    Type: AWS::CloudFront::OriginRequestPolicy
    Properties:
      OriginRequestPolicyConfig:
        Name: DsOriginRequestPolicyGeo
        Comment: Works together with CacheRequestPolicyCompressionGeo
        HeadersConfig:
          HeaderBehavior: whitelist
          Headers:
            - CloudFront-Viewer-Country-Name
            - CloudFront-Viewer-City
        CookiesConfig:
          CookieBehavior: none
        QueryStringsConfig:
          QueryStringBehavior: none

  # CacheRequestPolicy added for gzip/brotli compression and users Location tracking
  CachePolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        Comment: Same as CachingOptimized (658327ea-f89d-4fab-a63d-7e88639e58f6) but with extra geo headers
        DefaultTTL: 86400
        MaxTTL: 31536000
        MinTTL: 1
        Name: CacheRequestPolicyCompressionGeo
        ParametersInCacheKeyAndForwardedToOrigin:
          CookiesConfig:
            CookieBehavior: none
          EnableAcceptEncodingBrotli: true
          EnableAcceptEncodingGzip: true
          HeadersConfig:
            HeaderBehavior: whitelist
            Whitelist:
              - CloudFront-Viewer-Country-Name
              - CloudFront-Viewer-City
          QueryStringsConfig:
            QueryStringBehavior: none

Outputs:
  CloudFrontDistributionDomainName:
    Description: CloudFront distribution
    Value: !GetAtt CloudFrontDistribution.DomainName

  CloudFrontWebsiteAdress:
    Description: Website address
    Value: !Sub '${SubDomain}.${DomainName}'
