AWSTemplateFormatVersion: '2010-09-09'
Description: ACFS3 - Cert Provider with DNS validation
Transform: AWS::Serverless-2016-10-31

# see description of params in main.yaml
Parameters:
  S3BucketRootName:
    Type: String
  S3BucketLogsName:
    Type: String
  CopyLayerVersionName:
    Type: String
  CopyFunctionName:
    Type: String

Resources:
  CopyCustomResource:
    Type: 'AWS::CloudFormation::CustomResource'
    Properties:
      ServiceToken: !GetAtt CopyFunction.Arn 
      ServiceTimeout: 30

  S3BucketLogs:
    Type: AWS::S3::Bucket
    # will not be deleted in cascade if the cloudFormation stack is deleted
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref S3BucketLogsName
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      Tags:
        - Key: YourBrand Website Solution
          Value: ACFS3

  # NOTEs: 
  # 1. The root bucket doesn't need to be configured as a static website because this is not required
  # when Cloud Front handles routing like 404s, index.html, etc. Communication happens via REST API
  # 2. websiteConfiguration: {...} is not required for that reason
  # 3. the bucket is not public (and shouldn't be)
  S3BucketRoot:
    Type: AWS::S3::Bucket
    # will not be deleted in cascade if the cloudFormation stack is deleted
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref S3BucketRootName
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LoggingConfiguration:
        DestinationBucketName: !Ref 'S3BucketLogsName'
        LogFilePrefix: 'origin/'
      Tags:
        - Key: YourBrand Website Solution
          Value: ACFS3

  CopyLayerVersion:
    Type: 'AWS::Serverless::LayerVersion'
    Properties:
      LayerName: !Ref CopyLayerVersionName
      ContentUri: ../witch.zip
      CompatibleRuntimes:
        - nodejs20.x

  CopyRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: S3CopyPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                  - s3:PutObject
                  - s3:PutObjectAcl
                Resource:
                  - !Sub
                    - arn:aws:s3:::${TargetBucket}/*
                    - TargetBucket: !Ref S3BucketRoot
                  - !Sub
                    - arn:aws:s3:::${TargetBucket}
                    - TargetBucket: !Ref S3BucketRoot

  CopyFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Ref CopyFunctionName
      CodeUri: ../www
      Environment:
        Variables:
          BUCKET: !Ref S3BucketRoot
      Handler: witch.staticHandler
      Layers:
        - !Ref CopyLayerVersion
      Role: !GetAtt CopyRole.Arn
      Runtime: nodejs20.x
      Timeout: 300

Outputs:
  S3BucketRoot:
    Description: Website bucket
    Value: !Ref S3BucketRoot
  S3BucketRootDomainName:
    Description: Website bucket domain name
    Value: !GetAtt S3BucketRoot.DomainName
  S3BucketRootArn:
    Description: Website bucket locator
    Value: !GetAtt S3BucketRoot.Arn
  S3BucketLogs:
    Description: Logging bucket
    Value: !Ref S3BucketLogs
  S3BucketLogsDomainName:
    Description: Logging bucket domain name ex. customname.s3.us-east-1.amazonaws.com
    Value: !GetAtt S3BucketLogs.DomainName
  CopyFunction:
    Description: S3 helper function
    Value: !GetAtt CopyFunction.Arn
