AWSTemplateFormatVersion: 2010-09-09
Description: | 
  Deploys a secure static website on AWS using Amazon S3 and CloudFront with
  an ACM certificate, Origin Access Control (OAC), and modern caching and
  security best practices

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Domain
        Parameters:
          - SubDomain
          - DomainName

Mappings:
  Solution:
    Constants:
      Version: 'v0.12'

Rules:
  OnlyUsEast1:
    Assertions:
      - Assert:
          Fn::Equals:
            - !Ref AWS::Region
            - us-east-1
        AssertDescription: |
          This template can only be deployed in the us-east-1 region.
          This is because the ACM Certificate must be created in us-east-1

Parameters:
  # custom-resource params
  S3BucketRootName:
    Description: the name of the bucket that will have the website contents
    Type: String
    Default: "example.com"
  S3BucketLogsName:
    Description: the name of the bucket that will contain the logs related to the website
    Type: String
    Default: "example.com.logs"
  CopyLayerVersionName:
    Description: the name of the lambda layer version
    Type: String
    Default: "examplecom-lambda-layer-version"
  CopyFunctionName:
    Description: the name of the lambda function that uploads www/ assets to s3 bucket 
    Type: String
    Default: "examplecom-lambda"
  # acm-certificate params
  SubDomain:
    Description: The part of a website address before your DomainName - e.g. www or img
    Type: String
    Default: www
    AllowedPattern: ^[^.]*$
  DomainName:
    Description: The part of a website address after your SubDomain - e.g. example.com
    Type: String
    Default: example.com
  HostedZoneId:
    Description: HostedZoneId for the domain e.g. Z23ABC4XYZL05B
    Type: String
    Default: MUST_SPECIFY_AN_ID
  CreateApex:
    Description: Create an Apex Alias in CloudFront distribution - yes/no
    Type: String
    Default: "yes"
    AllowedValues: ["yes", "no"]
  # cloufdront-site params
  Response404File:
    Description: the html file to redirect 404 erorrs ex. 404.html
    Type: String
    Default: "/404.html"
  Response403File:
    Description: the html file to redirect 403 erorrs ex. 403.html
    Type: String
    Default: "/403.html"

Resources:
  CustomResourceStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./custom-resource.yaml
      Parameters:
        S3BucketRootName: !Ref S3BucketRootName
        S3BucketLogsName: !Ref S3BucketLogsName
        CopyLayerVersionName: !Ref CopyLayerVersionName
        CopyFunctionName: !Ref CopyFunctionName
      Tags:
        - Key: YourBrand Website Solution
          Value: ACFS3

  AcmCertificateStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./acm-certificate.yaml
      Parameters:
        SubDomain: !Ref SubDomain
        DomainName: !Ref DomainName
        CreateApex: !Ref CreateApex
        HostedZoneId: !Ref HostedZoneId
      Tags:
        - Key: YourBrand Website Solution
          Value: ACFS3

  CloudFrontStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./cloudfront-site.yaml
      Parameters:
        CertificateArn: !GetAtt AcmCertificateStack.Outputs.CertificateArn
        DomainName: !Ref DomainName
        SubDomain: !Ref SubDomain
        CreateApex: !Ref CreateApex
        S3BucketRoot: !GetAtt CustomResourceStack.Outputs.S3BucketRoot
        S3BucketRootDomainName: !GetAtt CustomResourceStack.Outputs.S3BucketRootDomainName
        S3BucketRootArn: !GetAtt CustomResourceStack.Outputs.S3BucketRootArn
        S3BucketLogs: !GetAtt CustomResourceStack.Outputs.S3BucketLogs
        S3BucketLogsDomainName: !GetAtt CustomResourceStack.Outputs.S3BucketLogsDomainName
        Response404File: !Ref Response404File
        Response403File: !Ref Response403File
      Tags:
        - Key: YourBrand Website Solution
          Value: ACFS3

Outputs:
  SolutionVersion:
    Value: !FindInMap [Solution, Constants, Version]
  CopyFunction:
    Description: S3 helper function
    Value: !GetAtt CustomResourceStack.Outputs.CopyFunction
  S3BucketLogs:
    Description: Logging bucket
    Value: !GetAtt CustomResourceStack.Outputs.S3BucketLogs
  S3BucketRoot:
    Description: Website bucket
    Value: !GetAtt CustomResourceStack.Outputs.S3BucketRoot
  S3BucketLogsDomainName:
    Description: Logging bucket domain name
    Value: !GetAtt CustomResourceStack.Outputs.S3BucketLogsDomainName
  S3BucketRootDomainName:
    Description: Website bucket domain name
    Value: !GetAtt CustomResourceStack.Outputs.S3BucketRootDomainName
  CertificateArn:
    Description: Issued certificate
    Value: !GetAtt AcmCertificateStack.Outputs.CertificateArn
  CloudFrontDistributionDomainName:
    Description: CloudFront distribution
    Value: !GetAtt CloudFrontStack.Outputs.CloudFrontDistributionDomainName
  CloudFrontWebsiteAdress:
    Description: Website address
    Value: !GetAtt CloudFrontStack.Outputs.CloudFrontWebsiteAdress
